### ISSUE TITLE
Will s.el drop the support of Emacs 23?

### ISSUE THREAD

**Issue by cireu** [magnars/s.el#132]
I'm going to write some new function for advanced unicode manipulation, such
as split string semantically like [grapheme-splitter](https://github.com/orling/grapheme-splitter), if s.el can drop the support of Emacs23, I can more built-in package like `pcase` and `cl-lib` to simplify the work.

And we can enable lexical binding for better performance.

**Comment by jasonm23** [comment]
@magnars - should consider when updating Travis/CI.

**Comment by magnars** [comment]
`s.el` is a library that is being used by lots of packages and lots of people, so I am wary of dropping support of older Emacsen. However, maybe Emacs 23 is old enough to warrant it regardless. I would be interested to hear if @purcell has any input on this.

**Comment by jasonm23** [comment]
@purcell - Hi Steve, any thoughts?

**Comment by jasonm23** [comment]
Related to backwards compatibility / testing capability for the package to robustly support older Emacs versions.  We have access to 24.x and up via Steve's `purcell/setup-emacs@v3.0`.

There's a couple of caveats specific to GitHub actions as CI.

- [24.x fails to pass tests on GH Actions](https://github.com/emacsfodder/s.el/runs/7853793103?check_suite_focus=true)

- [26.x fails to pass tests on GH Actions](https://github.com/emacsfodder/s.el/runs/7853793103?check_suite_focus=true)

However on a local run the tests pass on 26.3 as illustrated below:

![](https://user-images.githubusercontent.com/71587/184837750-9f19d362-ed34-4bbb-b88a-f20abe2028ad.png)

Potentially this can be mitigated using a different CI, or using Docker containers instead of the standard GH Action internal runners.

# The other question...

Do we really need to support Emacs prior to 27.1?  I have no data on usage of legacy versions.  Does anyone?

**Comment by purcell** [comment]
I think it's 100% fine to not support Emacs 23. I think at this stage you could also reasonably drop Emacs 24, to be honest, if it causes any extra maintainer overhead here. The last 24.x release was 2015-04-10, almost 7.5 years ago.

**Comment by magnars** [comment]
With Steve's blessing, I vote we drop support for 23, since that will give us some decent improvements.

**Comment by jasonm23** [comment]
Resolved as dropping Emacs 23.x support.
