### ISSUE TITLE
🐣 [REQUEST] - s-url-encode / s-url-decode

### ISSUE THREAD

**Issue by jasonm23** [magnars/s.el#156]
### Implementation PR

TBA

### Reference Issues

None

### Summary

- [ ] `(s-url-encode s)` - URL encode a string
- [ ] `(s-url-decode s)` - URL decode a string

### s-url-encode
```
(s-url-encode "hello world") => "hello%20world"
```

### s-url-decode
```
(s-url-decode "hello%20world") => "hello world"
```

### Drawbacks

Can't think of any drawbacks, no API breakages, seems to me to be in package goals/scope.

**Comment by jasonm23** [comment]
@magnars - added new issue templates, please give 'em a look / comments.

**Comment by jasonm23** [comment]
@magnars - this feature suggestion is in package scope, right?

**Comment by magnars** [comment]
This is already part of emacs core as `url-encode-url` and `url-dehex-string`

**Comment by jasonm23** [comment]
I assumed we were making `s` wrap inconsistent APIs from core?

**Comment by magnars** [comment]
We did do that for a select few very central string manipulation tools, to increase discoverability. I don't think we should extend that very much.

**Comment by jasonm23** [comment]
I figured the asymmetry of the **url-encode-url** / **url-de~~code~~hex-string** to be that sort of discoverability issue.

Pros/Cons?

Pros

- Only aliases.
- Aid users confused by the name `url-dehex-string`, who would likely be looking for a missing `url-decode-string` (or in the inverse case `string-encode-url`!) 
- Little additional code to maintain.
- Seems to match the API philosophy.

Cons

- People depending on `s.el` for just `s-url-encode` / `s-url-decode`?
- tbf I'm not seeing a real con.

Ultimately it's your sign-off that decides.  Just wanted to make the case.

**Comment by magnars** [comment]
I added the simple wrappers so that people wouldn't look for things like `split-string` and `equals` and not find them, then complaining in issues that the string library didn't have the most basic of utils. At first I didn't want to do that, but that's how it ended up. I wouldn't say it's the API philosophy to add aliases for everything to do with strings.

As for the specific case here, I feel it is more in the domain of URLs than strings, much like how formatting of phone numbers would not fit into the library.

So, cons:

- Unnecessarily grows the code and the API
- Adds another dependency to s.el
- Opens for all sorts of other pull requests of handy functions from other domains

In my opinion. It's not very important to me. I wouldn't be angry if it was indeed added. But you did ask for my opinion. 😊

**Comment by jasonm23** [comment]
> but I will likely do so eventually. 

I should say **maybe** here.

**Comment by jasonm23** [comment]
I'll close this one to keep it off the open issues.
