### ISSUE TITLE
Functions not visibile despite "require" mention

### ISSUE THREAD

**Issue by pkhoueiry** [magnars/s.el#66]
Dear Magnar,
Many thanks for the wonderful packages that you provide.
I came across "s.el" that I downloaded via elap. I find it contains many interesting functions. Despite the mention (require 's), the functions are not visibile from within emacs buffers. 

However, as example,  M-x describe-function RET s-collapse-whitespace works well

Is there a way to make these functions applicable on marked text in emacs buffers ?

Here are the two lines relative to s.el in my .emacs
(add-to-list 'load-path "~/.emacs.d/elpa/s-20140714.707")
(require 's)

Many thanks in advance ...
P.K

**Comment by madhavan020985** [comment]
I am facing the same issue as pkhoueiry. When i do describe-function, it works. but, when i call it from my interactive script, it failed. again, i went with rnkn's idea of defining a new function with interactive form added. even post that fix, it didn't work & it says, "-s-index-of: Symbol's function definition is void: \".
my .emacs file change for s.el,,
(load-file "~/.emacs.d/others/s.el")

**Comment by magnars** [comment]
This does not look like the same issue. You're calling `s` from a script, as intended. Seems like there are some problems with loading, tho. I cant spot it from your code - it looks perfectly fine. The only strange thing is that you're using `load-file` instead of the normally used `require`, but that shouldn't cause the issues you're seeing.

**Comment by madhavan020985** [comment]
hi magnars, it is a non-issue... your reply helped me understand it better.
i see your s.el is very popular & i liked it. but one commonly used function, last-index-of  a character (or) pattern in a string is missing in the api catalog.
i tried to implement it using elisp string-match, but since it can't be tuned to search from backward, i couldn't do it.
